version: "3"
services: 
    python-rest:
        build:
            context: ./python-rest
            dockerfile: Dockerfile
        image: benchmark:python-rest
        container_name: python-rest
        ports: 
            - 3001:8080

    pypy-rest:
        build:
            context: ./pypy-rest
            dockerfile: Dockerfile
        image: benchmark:pypy-rest
        container_name: pypy-rest
        ports: 
            - 3002:8080

    node-rest:
        build:
            context: ./node-rest
            dockerfile: Dockerfile
        image: benchmark:node-rest
        container_name: node-rest
        ports: 
            - 3003:3000

    deno-rest:
        build:
            context: ./deno-rest
            dockerfile: Dockerfile
        image: benchmark:deno-rest
        container_name: deno-rest
        ports: 
            - 3004:3000

    go-rest:
        build:
            context: ./go-rest
            dockerfile: Dockerfile
        image: benchmark:go-rest
        container_name: go-rest
        ports: 
            - 3005:3000

    # rust-rest:
    #     build:
    #         context: ./rust-rest
    #         dockerfile: Dockerfile
    #     image: benchmark:rust-rest
    #     container_name: rust-rest
    #     ports: 
    #         - 3006:8080

    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        image: benchmark:client
        container_name: client
        environment:
            LOG_LEVEL: "INFO"
            COUNT: 2000
            HOSTS: "python-rest:8080,pypy-rest:8080,node-rest:3000,deno-rest:3000,go-rest:3000"
        depends_on: 
            - python-rest
            - pypy-rest
            - node-rest
            - deno-rest
            - go-rest
