version: "3"
services: 
    python-rest:
        build:
            context: ./python-rest
            dockerfile: Dockerfile
        image: benchmark:python-rest
        container_name: python-rest
        ports: 
            - 3001:8080

    pypy-rest:
        build:
            context: ./pypy-rest
            dockerfile: Dockerfile
        image: benchmark:pypy-rest
        container_name: pypy-rest
        ports: 
            - 3002:8080

    node-rest:
        build:
            context: ./node-rest
            dockerfile: Dockerfile
        image: benchmark:node-rest
        container_name: node-rest
        ports: 
            - 3003:3000

    # deno-rest:
    #     build:
    #         context: ./deno-rest
    #         dockerfile: Dockerfile
    #     image: benchmark:deno-rest
    #     container_name: deno-rest
    #     ports: 
    #         - 3004:8000

    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        image: benchmark:client
        container_name: client
        environment:
            LOG_LEVEL: "INFO"
            COUNT: 10
            HOSTS: "python-rest:8080,pypy-rest:8080,node-rest:3000"
        depends_on: 
            - python-rest
            - pypy-rest
            - node-rest
